In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\AHAMMED\BIA_DATA_SCIENCE\Data_Visulization\Dataset\amazon_prime_titles.csv")

In [6]:
df.head(5)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",Canada,"March 30, 2021",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",India,"March 30, 2021",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",United States,"March 30, 2021",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",United States,"March 30, 2021",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",United Kingdom,"March 30, 2021",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9668 entries, 0 to 9667
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       9668 non-null   str
 1   type          9668 non-null   str
 2   title         9668 non-null   str
 3   director      7585 non-null   str
 4   cast          8435 non-null   str
 5   country       672 non-null    str
 6   date_added    155 non-null    str
 7   release_year  9668 non-null   int64
 8   rating        9331 non-null   str
 9   duration      9668 non-null   str
 10  listed_in     9668 non-null   str
 11  description   9668 non-null   str
dtypes: int64(1), str(11)
memory usage: 906.5 KB

In [13]:
df.shape

(9668, 12)

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2083
cast            1233
country         8996
date_added      9513
release_year       0
rating           337
duration           0
listed_in          0
description        0
dtype: int64

In [17]:
df=df.drop(columns="country")

In [18]:
df=df.drop(columns="date_added")

In [19]:
df.head()

,show_id,type,title,director,cast,release_year,rating,duration,listed_in,description
0,s1,Movie,The Grand Seduction,Don McKellar,"Brendan Gleeson, Taylor Kitsch, Gordon Pinsent",2014,NaN,113 min,"Comedy, Drama",A small fishing village must procure a local d...
1,s2,Movie,Take Care Good Night,Girish Joshi,"Mahesh Manjrekar, Abhay Mahajan, Sachin Khedekar",2018,13+,110 min,"Drama, International",A Metro Family decides to fight a Cyber Crimin...
2,s3,Movie,Secrets of Deception,Josh Webber,"Tom Sizemore, Lorenzo Lamas, Robert LaSardo, R...",2017,NaN,74 min,"Action, Drama, Suspense",After a man discovers his wife is cheating on ...
3,s4,Movie,Pink: Staying True,Sonia Anderson,"Interviews with: Pink, Adele, Beyoncé, Britney...",2014,NaN,69 min,Documentary,"Pink breaks the mold once again, bringing her ..."
4,s5,Movie,Monster Maker,Giles Foster,"Harry Dean Stanton, Kieran O'Brien, George Cos...",1989,NaN,45 min,"Drama, Fantasy",Teenage Matt Banting wants to work with a famo...

In [20]:
df["rating"] = df["rating"].fillna(df["rating"].mode()[0])

In [21]:
df["rating"].mode()[0]

'13+'

In [22]:
df["director"]=df["director"].fillna("Unknown Director")

In [23]:
df["cast"]=df["cast"].fillna("Unknown cast")

In [24]:
df.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [26]:
df.to_csv(r"C:\AHAMMED\BIA_DATA_SCIENCE\Data_Visulization\Dataset\amazon_prime_clean.csv")