In [ ]:
##pip install pandas

Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in .\venv\Lib\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in .\venv\Lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in .\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl (9.9 MB)
Using cached tzdata-2026.2-py2.py3-none-any.whl (349 kB)
Installing collected packages: tzdata, pandas

   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   ---------------------------------------- 0/2 [tzdata]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed pandas-3.0.2 tzdata-2026.2
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import nummpy as np
import pandas

ModuleNotFoundError: No module named 'nummpy'

In [5]:
import numpy as np
import pandas as pd

arr=np.array([1,2,3,4,5])
df=pd.DataFrame(arr,columns=['age'])
print(df)
display(df)

   age
0    1
1    2
2    3
3    4
4    5

   age
0    1
1    2
2    3
3    4
4    5

In [9]:
import numpy as np  
import pandas as pd
zeros = np.zeros((3,3))
df=pd.DataFrame(zeros)
display(df)

     0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  0.0  0.0  0.0

In [10]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [11]:
line_arr=np.linspace(1,10,5)
print("line arr",line_arr)

line arr [ 1.    3.25  5.5   7.75 10.  ]

In [12]:
rand_arr=np.random.rand(3,3)
print("rand arr",rand_arr)

rand arr [[1.76830472e-05 7.55195380e-01 3.28180701e-01]
 [7.16441559e-01 5.57171896e-01 8.86406255e-01]
 [4.96914669e-01 2.03781610e-01 5.87021951e-02]]

In [14]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
element=arr[1,1]
print("element at first row and first column",element)

element at first row and first column 5

In [17]:
mask=arr>5
filtered=arr[mask]
print("boolen mask for values greater than 5:/n",mask)
print("filtered array with values greater than 5:/n",filtered)

boolen mask for values greater than 5:/n [[False False False]
 [False False  True]
 [ True  True  True]]
filtered array with values greater than 5:/n [6 7 8 9]

In [19]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

b=a[:2,1:3]
print("sliced array b:",b)

sliced array b: [[2 3]
 [5 6]]

In [20]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

In [21]:
addition=arr1+arr2
print("addition of arr1 and arr2:",addition)

addition of arr1 and arr2: [5 7 9]

In [22]:
subtraction=arr1-arr2
print("subtraction of arr1 and arr2:",subtraction)

subtraction of arr1 and arr2: [-3 -3 -3]

In [23]:
multiplication=arr1*arr2
print("multiplication of arr1 and arr2:",multiplication)

multiplication of arr1 and arr2: [ 4 10 18]

In [24]:
division=arr1/arr2
print("division of arr1 and arr2:",division)

division of arr1 and arr2: [0.25 0.4  0.5 ]

In [26]:
arr1 = np.array([10, 29, 30, 40, 50, 60])

mean_arr1 = np.mean(arr1)
std_dev_arr1 = np.std(arr1)

print("Mean of arr1:", mean_arr1)
print("Standard deviation of arr1:", std_dev_arr1)

Mean of arr1: 36.5
Standard deviation of arr1: 16.05978414134719

In [29]:
import numpy as np  
arr1=np.array([1,4,16])
result_sqrt=np.sqrt(arr1)
print("square root of arr1:",result_sqrt)

square root of arr1: [1. 2. 4.]

In [30]:
arr1=np.array([0,np.pi/2,np.pi])
result_sin=np.sin(arr1)
print("sine of arr1:",result_sin)

sine of arr1: [0.0000000e+00 1.0000000e+00 1.2246468e-16]

In [31]:
arr1=np.array([0,np.pi/2,np.pi])
result_sin=np.cos(arr1)
print("cosine of arr1:",result_sin)

cosine of arr1: [ 1.000000e+00  6.123234e-17 -1.000000e+00]

In [33]:
arr1=np.array([1,2,3])
result_log=np.log(arr1)
print("logarithm of arr1:",result_log)

logarithm of arr1: [0.         0.69314718 1.09861229]

In [34]:
import pandas as pd
data=[10,20,30,40,50]
series_from_list=pd.Series(data)
print("Series from list:",series_from_list)

Series from list: 0    10
1    20
2    30
3    40
4    50
dtype: int64

In [35]:
data={"name":["alice","ahammed","ahad","sameer"],
        "age":[25,30,35,40],
        "city":["new york","los angeles","chicago","houston"]}
df=pd.DataFrame(data)
print("DataFrame from dictionary:",df)

DataFrame from dictionary:       name  age         city
0    alice   25     new york
1  ahammed   30  los angeles
2     ahad   35      chicago
3   sameer   40      houston